#!/bin/sh
#
# Wait for mysql to get available and initialize/upgrade the database if needed
# https://github.com/artem-sidorenko/docker-base-centos
#
# Author Artem Sidorenko artem@2realities.com
#
# Copyright 2015 Artem Sidorenko and contributors.
# See the COPYRIGHT file at the top-level directory of this distribution
# and at https://github.com/artem-sidorenko/docker-base-centos/blob/master/COPYRIGHT
#

# Following environment variables are expected:
#
# - APP_VERSION
# - MYSQL_HOST
# - MYSQL_PORT
# - MYSQL_DATABASE
# - MYSQL_USER
# - MYSQL_PASSWORD
# - MYSQL_INIT_CMD
# - MYSQL_UPGRADE_CMD

MYSQL_LOOPS="10"
DATABASE_VERSION_FILE="/var/lib/docker-state/db/version"

#wait for mysql
i=0
while ! nc $MYSQL_HOST $MYSQL_PORT >/dev/null 2>&1 < /dev/null; do
  i=`expr $i + 1`
  if [ $i -ge $MYSQL_LOOPS ]; then
    echo "$(date) - ${MYSQL_HOST}:${MYSQL_PORT} still not reachable, giving up"
    exit 1
  fi
  echo "$(date) - waiting for ${MYSQL_HOST}:${MYSQL_PORT}..."
  sleep 1
done

#if mysql env vars are configured, continue with DB initialization
if [ -n "$MYSQL_DATABASE" -a -n "$MYSQL_USER" -a -n "$MYSQL_PASSWORD" ]; then
  table_count=$(echo "show tables;" | mysql -N -h $MYSQL_HOST -u $MYSQL_USER --pas
sword=$MYSQL_PASSWORD $MYSQL_DATABASE | wc -l)
  if [ "$table_count" = "0" ]; then
    #no tables, lets init the database
    echo "$(date) - initializing the database..."
    $MYSQL_INIT_CMD
    mkdir -p $(dirname "${DATABASE_VERSION_FILE}")
    echo "${APP_VERSION}" > "${DATABASE_VERSION_FILE}"
  else
    #check if we need to upgrade the db
    if [ ! -e $DATABASE_VERSION_FILE -o "$(cat $DATABASE_VERSION_FILE)" != "$APP_VERSION" ]; then
      echo "$(date) - new version detected, upgrading the database..."
      $MYSQL_UPGRADE_CMD
      mkdir -p $(dirname "${DATABASE_VERSION_FILE}")
      echo "${APP_VERSION}" > "${DATABASE_VERSION_FILE}"
    fi
  fi
fi
